from Enums.skill import Skill
from Enums.uncommon_skill import UncommonSkill


class SkillsInfo():
    skills_base_points = {
        Skill.ACCOUNTING: 5,
        Skill.ANTHROPOLOGY: 1,
        Skill.APPRAISE: 5,
        Skill.ARCHAEOLOGY: 1,
        Skill.ART_CRAFT: 5,
        Skill.CHARM: 15,
        Skill.CLIMB: 20,
        Skill.CREDIT_RATING: 0,
        Skill.CTHULHU_MYTHOS: 0,
        Skill.DISGUISE: 5,
        Skill.DODGE: "0.5 DEX",
        Skill.DRIVE_AUTO: 20,
        Skill.ELECTRICAL_REPAIR: 10,
        Skill.FAST_TALK: 5,
        Skill.FIGHTING: 25,
        Skill.FIREARMS: 20,
        Skill.FIRST_AID: 30,
        Skill.HISTORY: 5,
        Skill.INTIMIDATE: 15,
        Skill.JUMP: 20,
        Skill.OTHER_LANGUAGE: 1,
        Skill.OWN_LANGUAGE: "EDU",
        Skill.LAW: 5,
        Skill.LIBRARY_USE: 20,
        Skill.LISTEN: 20,
        Skill.LOCKSMITH: 1,
        Skill.MECHANICAL_REPAIR: 10,
        Skill.MEDICINE: 1,
        Skill.NATURAL_WORLD: 10,
        Skill.NAVIGATE: 10,
        Skill.OCCULT: 5,
        Skill.OPERATE_HEAVY_MACHINERY: 1,
        Skill.PERSUADE: 10,
        Skill.PILOT: 1,
        Skill.PSYCHOLOGY: 10,
        Skill.PSYCHOANALYSIS: 1,
        Skill.RIDE: 5,
        Skill.SCIENCE: 1,
        Skill.SLEIGHT_OF_HAND: 10,
        Skill.SPOT_HIDDEN: 25,
        Skill.STEALTH: 20,
        Skill.SURVIVAL: 10,
        Skill.SWIM: 20,
        Skill.THROW: 20,
        Skill.TRACK: 10,
        Skill.DIVING: 1,
        UncommonSkill.ANIMAL_HANDLING: 5,
        UncommonSkill.ARTILLERY: 1,
        UncommonSkill.DEMOLITIONS: 1,
        UncommonSkill.HYPNOSIS: 1,
        UncommonSkill.READ_LIPS: 1
    }
